version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: test_app
    ports:
      - "8080:8080"
    volumes:
      - ../app:/go/src/app
    links:
      - db
    depends_on: 
      - db
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: test_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports: 
      - ${DB_PORT}:3306
    volumes:
      - ./db/mysql/lib:/var/lib/mysql
      - ./db/mysql/logs:/var/log/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d