version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: test_app
    ports:
      - "8080:8080"
    volumes:
      - ../app:/go/src/app
    links:
      - db
    depends_on: 
      - db
  db:
    build: 
      context: .
      dockerfile: ./db/Dockerfile
    container_name: test_db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
      hostname: test_db
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/log/mysql

volumes:
  db_data:
    driver: local
